import {readFileSync,writeFileSync} from 'node:fs';
const backend = readFileSync(new URL('../apps-script/Code.gs',import.meta.url),'utf8');
const mock = `// Generated by scripts/build-demo.mjs. Same rules as Apps Script; memory only.
export function createDemoService() {
  const tables = new Map(), cache = new Map(), props = new Map();
  const chain = {setFontWeight:()=>chain,setBackground:()=>chain};
  class Sheet {
    constructor(){this.rows=[];}
    appendRow(row){this.rows.push([...row]);}
    getLastRow(){return this.rows.length;}
    setFrozenRows(){}
    getDataRange(){return {getValues:()=>this.rows.map(r=>[...r])};}
    deleteRow(index){this.rows.splice(index-1,1);}
    getRange(row,col,height,width){return {...chain,getValues:()=>Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>this.rows[row-1+i]?.[col-1+j]??'')),setValues:values=>values.forEach((r,i)=>{this.rows[row-1+i]??=[];r.forEach((v,j)=>{this.rows[row-1+i][col-1+j]=v;});})};}
  }
  const ss={getSheetByName:n=>tables.get(n),insertSheet:n=>{const s=new Sheet();tables.set(n,s);return s;},getId:()=> 'demo',getSpreadsheetTimeZone:()=> 'Asia/Taipei',toast:()=>{}};
  const SpreadsheetApp={getActiveSpreadsheet:()=>ss,openById:()=>ss,getUi:()=>({}),flush:()=>{}};
  const PropertiesService={getScriptProperties:()=>({getProperty:k=>props.get(k)||null,setProperty:(k,v)=>props.set(k,v)})};
  const CacheService={getScriptCache:()=>({get:k=>{const v=cache.get(k);return v&&v.until>Date.now()?v.value:null;},put:(k,v,s)=>cache.set(k,{value:v,until:Date.now()+s*1000}),remove:k=>cache.delete(k)})};
  const LockService={getScriptLock:()=>({waitLock:()=>{},releaseLock:()=>{}})};
  // Cache keys do not need cryptographic hashing in this isolated preview.
  const Utilities={getUuid:()=>crypto.randomUUID(),DigestAlgorithm:{SHA_256:'sha256'},computeDigest:(_,v)=>Array.from(new TextEncoder().encode(v)),formatDate:(date,timeZone)=>new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(date)};
  const UrlFetchApp={fetch:()=>{throw new Error('示範不呼叫 Google');}};
`;
const seed = `
  setup_();
  append_('Users',['preview.member@example.com','示範同事','產品部','member',true,'demo-member']);
  append_('Users',['preview.other@example.com','另一位示範同事','營運部','member',true,'demo-other']);
  const examples=[['宜蘭','溫泉、山海散步與在地美食。',[4500,6500,'2 天 1 夜','遊覽車約 2 小時','溫泉旅館，雙人房','礁溪溫泉、蘭陽博物館、海岸散步','低至中，適合輕鬆散步','預算為示範估算；餐飲、交通與住宿需詢價。']],['台中','城市漫遊與山城風景，行程彈性較高。',[5000,7500,'3 天 2 夜','高鐵或遊覽車','市區飯店，雙人房','市區美食、后里自行車、特色咖啡','中，可調整自行車活動','預算為示範估算；熱門住宿需提早確認。']],['花蓮','東海岸慢旅行，欣賞自然景色。',[8000,11000,'3 天 2 夜','火車，加當地包車','海景旅宿，雙人房','海岸景色、地方文化、特色料理','中，部分戶外步行','預算為示範估算；景點開放狀況需出發前確認。']]];
  examples.forEach(([name,description,info],i)=>append_('Places',['demo-place-'+i,name,description,...info,'',i===2?'preview.other@example.com':'preview.member@example.com',now_(),false]));
  return {
    request: request=>Promise.resolve().then(()=>JSON.parse(JSON.stringify(api(request)))),
    login: email=>{const user=userByEmail_(email); if(!user.googleSub){const r=rows_('Users')[user.index];r[5]='demo-admin';write_('Users',user.index,r);user.googleSub=r[5];} const session=uid_(); CacheService.getScriptCache().put('session:'+digest_(session),JSON.stringify({email,sub:user.googleSub,expires:Date.now()+21600000}),21600);return {session,data:load_(user)};}
  };
}
`;
writeFileSync(new URL('../web/demo.js',import.meta.url),mock+backend+seed);
console.log('Demo regenerated from Apps Script rules');
